# Generated by Django 5.1.3 on 2025-02-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produits', models.ManyToManyField(related_name='ventes', to='produits.produit')),
            ],
        ),
    ]
